version: '3'

services:
  rcja-registration:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./rcjaRegistration:/app
    environment:
      - DATABASE_URL=postgres://rcjaRegistration:abc123@db/rcjaRegistration
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rcjaRegistration
      - POSTGRES_USER=rcjaRegistration
      - POSTGRES_PASSWORD=abc123

volumes:
  postgres_data:
