version: '3'

services:
  web:
    restart: unless-stopped
    image: rcja-registration:production
    build: .
    ports:
      - 8000:8000
    environment:
      - DEBUG=false
      - SECRET_KEY
  db:
    restart: unless-stopped
