version: '3'

services:
  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./rcjaRegistration:/app
    environment:
      - DEBUG=true
      - SECRET_KEY=u75_y555kb_-11g)u3f&3z5bk&+noj0!a4ddo8_8a%oqe6&tu!
      - DATABASE_URL=postgres://rcjaRegistration:abc123@db/rcjaRegistration
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rcjaRegistration
      - POSTGRES_USER=rcjaRegistration
      - POSTGRES_PASSWORD=abc123

volumes:
  postgres_data:
