name: Django Build Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Compose stack
      run: |
        docker-compose up -d
    - name: Lint with flake8
      run: |
        docker-compose exec -T web pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        docker-compose exec -T web flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker-compose exec -T web flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        DEBUG: true
        SECRET_KEY: xmc$&0neem3(yld1mzt+2vhw14u%gyrd4r&y7t7btflzh^ljk)
      run: |
        docker-compose exec -T web manage.py test
        #pip install pytest
        #pytest
    - name: Generate code coverage report
      run: |
        docker-compose exec -T web pip install coverage
        docker-compose exec -T web coverage run --source='.' manage.py test
        docker-compose exec -T web coverage report
        docker-compose exec -T web coverage xml
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./rcjaRegistration/coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
    - name: Tear down Docker Compose stack
      run: |
        docker-compose down